server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scr_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
#分页插件
pagehelper:
  reasonable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# type-aliases-package: com.scr.domain
# 打印sql语句
logging:
  level:
    com.scr.mapper: debug